# Generated by Django 3.0.4 on 2020-10-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('nasc', models.DateField()),
                ('img_url', models.TextField()),
            ],
            options={
                'db_table': 'artista',
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('url_play', models.TextField(db_column='youtube_url')),
                ('lancamento', models.TextField()),
                ('img_url', models.TextField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Artista')),
            ],
            options={
                'db_table': 'disco',
            },
        ),
    ]
